name: fetch-remote-json

permissions:
  contents: write  # 允许推送到仓库

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch: {}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 1

      - name: Set up git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Download specified json files from remote repo
        id: fetch
        env:
          REMOTE_OWNER: DustinWin
          REMOTE_REPO: ruleset_geodata
          REMOTE_BRANCH: sing-box-ruleset
          OUT_DIR: remote
        run: |
          set -eu
          mkdir -p "$OUT_DIR"
          files=("cn.json" "proxy.json")

          base_url="https://raw.githubusercontent.com/${REMOTE_OWNER}/${REMOTE_REPO}/${REMOTE_BRANCH}"
          changed=0

          for f in "${files[@]}"; do
            url="${base_url}/${f}"
            dest="${OUT_DIR}/${f}"
            tmp="${dest}.tmp"

            echo "Downloading $url -> $tmp"
            if curl -fsSL "$url" -o "$tmp"; then
              if [ -f "$dest" ]; then
                if cmp -s "$dest" "$tmp"; then
                  echo "No change for $f"
                  rm -f "$tmp"
                else
                  mv "$tmp" "$dest"
                  echo "Updated $dest"
                  changed=1
                fi
              else
                mv "$tmp" "$dest"
                echo "Created $dest"
                changed=1
              fi
            else
              echo "Warning: failed to download $url (skipping)"
              rm -f "$tmp" || true
            fi
          done

          echo "changed=$changed" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.fetch.outputs.changed == '1'
        run: |
          git add remote || true
          git commit -m "Update remote JSON files from DustinWin/ruleset_geodata"
          git push
